[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc = "0.8.27"
evm_version = "cancun"
remappings = [
    "@luxfi/contracts/=node_modules/@luxfi/contracts/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/"
]
